language: ruby
os: linux
dist: xenial
cache: bundler
rvm:
  - 2.7.0
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
script: bash -ex .travis-ci.sh
before_install:
- gem install bundler -v 2.0.2
